# Generated by Django 5.1.2 on 2025-01-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderServiceFee',
            new_name='ServiceFee',
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True),
        ),
    ]
