# Generated by Django 5.1.2 on 2025-01-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_rename_orderservicefee_servicefee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SurveyResident',
        ),
    ]
