# Generated by Django 5.1.2 on 2025-01-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_rename_servicefee_managingfees_and_more'),
        ('apartment', '0003_survey_content_delete_surveyresident'),
    ]

    operations = [
    ]
