# Generated by Django 5.1.2 on 2025-01-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_feevalue_remove_managingfees_value_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParkingFeeForRelatives',
            new_name='ParkingForRelatives',
        ),
    ]
