# Generated by Django 5.1.2 on 2025-01-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_rename_parkingfeeforrelatives_parkingforrelatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefees',
            name='fee_value',
            field=models.FloatField(blank=True),
        ),
    ]
