# Generated by Django 5.1.2 on 2025-01-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_alter_servicefees_fee_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
