# Generated by Django 5.1.2 on 2025-01-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_locker_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsinlocker',
            options={},
        ),
        migrations.RemoveField(
            model_name='itemsinlocker',
            name='active',
        ),
        migrations.RemoveField(
            model_name='itemsinlocker',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='itemsinlocker',
            name='updated_date',
        ),
    ]
