# Generated by Django 5.1.2 on 2025-01-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_merge_20250113_0927'),
        ('apartment', '0011_alter_resident_citizen_identification'),
    ]

    operations = [
    ]
