# Generated by Django 5.1.2 on 2025-01-22 12:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_merge_20250122_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='managingfees',
            name='status',
            field=models.BooleanField(choices=[(True, 'Đã thanh toán'), (False, 'Chưa thanh toán')], default=True),
        ),
        migrations.AddField(
            model_name='parkingfees',
            name='status',
            field=models.BooleanField(choices=[(True, 'Đã thanh toán'), (False, 'Chưa thanh toán')], default=True),
        ),
        migrations.AddField(
            model_name='servicefees',
            name='status',
            field=models.BooleanField(choices=[(True, 'Đã thanh toán'), (False, 'Chưa thanh toán')], default=True),
        ),
        migrations.AlterField(
            model_name='managingfees',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fee'),
        ),
        migrations.AlterField(
            model_name='parkingfees',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fee'),
        ),
        migrations.AlterField(
            model_name='servicefees',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fee'),
        ),
    ]
