# Generated by Django 5.1.2 on 2025-01-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0013_managingfees_status_parkingfees_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managingfees',
            name='status',
            field=models.BooleanField(choices=[(True, 'Đã thanh toán'), (False, 'Chưa thanh toán')], default=False),
        ),
        migrations.AlterField(
            model_name='parkingfees',
            name='status',
            field=models.BooleanField(choices=[(True, 'Đã thanh toán'), (False, 'Chưa thanh toán')], default=False),
        ),
        migrations.AlterField(
            model_name='servicefees',
            name='status',
            field=models.BooleanField(choices=[(True, 'Đã thanh toán'), (False, 'Chưa thanh toán')], default=False),
        ),
    ]
