# Generated by Django 5.1.2 on 2025-01-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0014_alter_managingfees_status_alter_parkingfees_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsinlocker',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='itemsinlocker',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemsinlocker',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsinlocker',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
