# Generated by Django 5.1.2 on 2025-01-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0015_alter_itemsinlocker_options_itemsinlocker_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyresident',
            unique_together={('survey', 'resident')},
        ),
    ]
