# Generated by Django 5.1.2 on 2025-01-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0017_locker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='change_password_image',
            field=models.BooleanField(default=False),
        ),
    ]
