# Generated by Django 5.1.2 on 2025-01-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0018_resident_change_password_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresident',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surveyresident',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresident',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
