# Generated by Django 5.1.2 on 2025-01-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresident',
            options={'ordering': ['-created_date']},
        ),
    ]
