# Generated by Django 5.1.2 on 2025-01-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_alter_surveyresident_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresident',
            options={},
        ),
    ]
