# Generated by Django 5.1.2 on 2025-01-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_surveyresident_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Resident', 'Resident')], default='Admin', max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
