# Generated by Django 5.1.2 on 2025-01-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='locker',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locker', to='apartment.resident'),
        ),
        migrations.AlterField(
            model_name='parkingforrelatives',
            name='phone_relative',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='servicefees',
            name='fee_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.feevalue'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.address'),
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tháng 1', 'Tháng 1'), ('Tháng 2', 'Tháng 2'), ('Tháng 3', 'Tháng 3'), ('Tháng 4', 'Tháng 4'), ('Tháng 5', 'Tháng 5'), ('Tháng 6', 'Tháng 6'), ('Tháng 7', 'Tháng 7'), ('Tháng 8', 'Tháng 8'), ('Tháng 9', 'Tháng 9'), ('Tháng 10', 'Tháng 10'), ('Tháng 11', 'Tháng 11'), ('Tháng 12', 'Tháng 12')], max_length=20)),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['year', 'name'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.AddField(
            model_name='managingfees',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartment.month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingfees',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartment.month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicefees',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartment.month'),
            preserve_default=False,
        ),
    ]
