# Generated by Django 5.1.2 on 2025-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_address_alter_locker_resident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='citizen_identification',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
