# Generated by Django 5.1.2 on 2025-01-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_alter_resident_citizen_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterUniqueTogether(
            name='managingfees',
            unique_together={('resident', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='parkingfees',
            unique_together={('resident', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='servicefees',
            unique_together={('resident', 'month')},
        ),
    ]
