# Generated by Django 5.1.2 on 2025-01-29 11:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_alter_month_year_alter_managingfees_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dqlk15sot/image/upload/v1738150398/default-avatar-profile-icon-of-social-media-user-vector_qydb7c.jpg', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
