# Generated by Django 5.1.2 on 2025-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='change_password_image',
        ),
        migrations.AddField(
            model_name='user',
            name='change_password_image',
            field=models.BooleanField(default=False),
        ),
    ]
