# Generated by Django 5.1.2 on 2025-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_remove_resident_change_password_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
