# Generated by Django 5.1.2 on 2025-02-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_address_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managingfees',
            name='fee_value',
        ),
        migrations.RemoveField(
            model_name='servicefees',
            name='fee_value',
        ),
        migrations.RemoveField(
            model_name='parkingfees',
            name='fee_value',
        ),
        migrations.DeleteModel(
            name='FeeValue',
        ),
    ]
