# Generated by Django 5.1.2 on 2025-02-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_remove_managingfees_fee_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managingfees',
            name='fee_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parkingfees',
            name='fee_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servicefees',
            name='fee_value',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
