# Generated by Django 5.1.2 on 2025-02-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0016_alter_month_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
