# Generated by Django 5.1.2 on 2025-02-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0017_alter_month_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresident',
            name='is_response',
            field=models.BooleanField(default=False),
        ),
    ]
