# Generated by Django 5.1.2 on 2025-02-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0018_surveyresident_is_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
    ]
