# Generated by Django 5.1.2 on 2025-02-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0020_alter_resident_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
