# Generated by Django 5.1.2 on 2025-02-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0023_itemsinlocker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='status',
        ),
    ]
