# Generated by Django 5.1.2 on 2025-02-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0025_parkingforrelatives_is_come'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingforrelatives',
            name='phone_relative',
            field=models.CharField(max_length=10),
        ),
    ]
