# Generated by Django 5.1.2 on 2025-02-05 13:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0027_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managingfees',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fee_image'),
        ),
        migrations.AlterField(
            model_name='parkingfees',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fee_image'),
        ),
        migrations.AlterField(
            model_name='servicefees',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fee_image'),
        ),
    ]
