# Generated by Django 5.1.2 on 2025-02-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0028_alter_managingfees_image_alter_parkingfees_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managingfees',
            old_name='image',
            new_name='fee_image',
        ),
        migrations.RenameField(
            model_name='parkingfees',
            old_name='image',
            new_name='fee_image',
        ),
        migrations.RenameField(
            model_name='servicefees',
            old_name='image',
            new_name='fee_image',
        ),
    ]
