# Generated by Django 5.1.2 on 2025-02-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0029_rename_image_managingfees_fee_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='resident',
            field=models.OneToOneField(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='locker', to='apartment.resident'),
        ),
    ]
