# Generated by Django 5.1.2 on 2025-02-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0032_alter_locker_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='resident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker', to='apartment.resident'),
        ),
    ]
