# Generated by Django 5.1.2 on 2025-02-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0033_alter_locker_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Resident', 'Resident')], default='Resident', max_length=20),
        ),
    ]
